### ISSUE TITLE
HPWH model results

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#838] opened 2021-08-30 16:49 UTC
It was reported that our generic HPWH model w/ EF=2.06 provides _higher_ energy use than EF=2.0. We may need to revisit our assumptions. For larger EF differences (e.g., jumping to EF=3.0), the HPWH does correctly provide lower energy use.

**Comment by jmaguire1** [comment] 2021-09-01 16:20
I did a fair amount of digging into this, and it turns out Uzair changed more than the HPWH efficiency between cases, and his other changes are why the HPWH model was less efficient, not just the change to the COP and capacity. Here's the email I sent him so we have it archived here:

Hi Uzair,

Hope you’re feeling better! I’m pretty sure I figured out what’s happening in your use case here. When I look at the two cases (EF=2.0 and EF=2.06), there’s actually a couple of things changing between the building models in those two cases, not just the HPWH efficiency and capacity. I made a third case that starts with the EF=2.0 E+ input file but ONLY change the capacity and COP of the HPWH and it looks like in this case we’re getting a very slight increase in the efficiency of the HPWH:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jmaguire/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jmaguire/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | EF = 2.00 | EF = 2.06 | EF = 2.06, WH   Change Only
-- | -- | -- | --
Consumed   Energy (kWh) | 1264.6 | 1333.1 | 1235.4
Backup Element   Energy (kWh) | 10.4 | 149.5 | 4.4
Heat Pump   Energy (kWh) | 1204.5 | 1134.9 | 1181.7
Delivered   Energy (kWh) | 2778.0 | 2643.3 | 2777.9
Annual   Efficiency | 2.20 | 1.98 | 2.25



</body>

</html>


I’ve attached this .idf as well so you can confirm yourself if you’d like. In general I think that the way that we have the HPWH set up right now is OK: HP capacity increases as COP increases. As the HP gets larger, it will be better able to meet the load without using the backup electric resistance element, which will lead to higher overall efficiencies. You can see this trend in the backup element usage decreasing as we go from an EF of 2.0 > 2.06 without changing anything else.

Naturally, this raises the question of what else is changing that might be influencing the water heater results in your case with an EF of 2.06. I haven’t fully traced down the root cause, but I have two suspects:

1.	The HPWH is installed in an unconditioned space (an unconditioned basement), and there’s different space temperatures between the two cases. In the EF = 2.0 case it looks like the ducts are in the basement but they move to the living space in your EF = 2.06 case, so it’s possible the duct losses are keeping the basement warmer in the winter and increasing the COP during that part of the year. 
2.	The dishwasher is different between the units, which means that the draw profile itself is actually changing between cases. I think this is unlikely to be the root cause since the annual average draw volume actually decreases in the EF 2.06 case you sent over, but it’s possible that the draws are more coincident and that’s leading to more backup element usage.

I think 1 is much more likely than 2, but I haven’t fully traced through exactly what’s causing the difference here beyond ruling out that just changing the COP and capacity alone being the root cause.

Hope this helps! Let me know if you want to discuss any of this more.

-Jeff

@shorowit: Do you want to do anything else here? The way we're changing the COP and capacity of the HPWH seems reasonable to me (capacity and COP both increase as EF/UEF increases, both of which should lead to higher annual efficiency) and if Uzair had only changed the COP and capacity of the HPWH then he would have seen the expected behavior.

**Comment by jmaguire1** [comment] 2021-09-07 17:58
It looks like they were in agreement that it was the installation location change, not the change in EF, that led to their surprising HPWH results. To keep everything archived in one place here was their response:

Hi Jeff and Scott, 

Thank you for the help looking in to this. We did a few tests and agree that the most likely explanation was that the HPWH was in the basement and the duct location change impacted HPWH energy use more than the small improvement in the EF. 

Thanks, 
Michael

@shorowit I'm going to close this issue since it seems like it's not actually a problem with how we change HPWH capacity as a function of EF, but you can definitely reopen it if you want to dig in any more here.

**Closed by jmaguire1** 2021-09-07 17:58 UTC
