### ISSUE TITLE
Template workflows not working with OpenStudio 3.7.0 and Ubuntu

### ISSUE THREAD

**Issue by ckm47** [NREL/OpenStudio-HPXML#1607] opened 2024-02-06 10:13 UTC
When using the template workflows on both Ubuntu 22 and Ubuntu 20 + OpenStudio 3.7.0 I get the following error: 

input
`openstudio run -w workflow/template-run-hpxml.osw`

output
```
The following argument was not expected: in.idf
Run with --help for more information.
[openstudio.workflow.OSWorkflow] <Fatal> EnergyPlus failed and did not create an eplusout.end file. Check the stdout-energyplus log.
[openstudio.workflow.OSWorkflow] <Error> Found error in state 'EnergyPlus' with message: '/srv/jenkins/openstudio/docker-volumes/ubuntu-2204-nightly/src/workflow/RunEnergyPlus.cpp@291 : EnergyPlus failed and did not create an eplusout.end file. Check the stdout-energyplus log.'
Failed to run workflow. Last Error:
  Found error in state 'EnergyPlus' with message: '/srv/jenkins/openstudio/docker-volumes/ubuntu-2204-nightly/src/workflow/RunEnergyPlus.cpp@291 : EnergyPlus failed and did not create an eplusout.end file. Check the stdout-energyplus log.
```

Configurations tried:
1. Not working : docker on OSX Sonoma, M2, platform linux/amd64, with Ubuntu 22.04 and OpenStudio 3.7.0, latest OpenStudio-HPXML https://github.com/NREL/OpenStudio-HPXML/commit/4f60b2e19cb413803022cbafef31d28e083f820e
2. Not working: Same as 1, but with Ubuntu 20.04
3. Not working: Same as 1 but with OpenStudio-HPXML set to last release 5b26ce2e9ec042ad9397096a32accbe53a7cf20b 
4. Not working: docker on Windows 10 Pro, platform linux/amd64, with Ubuntu 22.04 and OpenStudio 3.7.0, latest OpenStudio-HPXML 
5. Working: openstudio arm64 on OSX Sonoma with latest OpenStudio-HPXML
6. Working: openstudio amd64 on Windows 11 Pro with latest OpenStudio-HPXML

**Comment by shorowit** [comment] 2024-02-06 15:28
A similar issue was posted on [OpenStudio](https://github.com/NREL/OpenStudio/issues/5057), which eventually got moved to [EnergyPlus](https://github.com/NREL/EnergyPlus/issues/10322). Maybe you can add any relevant information to that issue. I'm going to close this because it seems unlikely that the issue is in OpenStudio-HPXML itself, but feel free to reopen if you disagree.

Note that our CI tests successfully run simulations on [Ubuntu 22.04](https://github.com/NREL/OpenStudio-HPXML/blob/4f60b2e19cb413803022cbafef31d28e083f820e/.github/workflows/config.yml#L12) using [OpenStudio 3.7.0](https://github.com/NREL/OpenStudio-HPXML/blob/4f60b2e19cb413803022cbafef31d28e083f820e/.github/workflows/config.yml#L14).

**Closed by shorowit** 2024-02-06 15:28 UTC

**Comment by ckm47** [comment] 2024-02-06 19:33
Thanks for the link. Definitely seems to be an Energy Plus issue.
